/** What the panel needs of a sound player. Fakes in tests count calls. */
export interface AudioPlayer {
  play(asset: string): void;
}

/** The one sound this app has. Generated by scripts/generate-fanfare.mjs. */
export const FANFARE = 'fanfare.wav';
